efemerides = {
	"1 de Enero":"Año Nuevo, Nace Manuel Felipe Tovar (1803), Se Establece el Matrimonio Civil en Venezuela (1873), Se inaugura El Aeropuerto Internacional de Maiquetía Simón Bolívar (1945), Nacionalización del Hierro (1975), Decreto que Prohíbe la Publicidad de Tabaco en la Televisión (1981), Decreto que Prohíbe la Publicidad en Radio y Televisión de Bebidas Alcohólicas (1982), Se funda La Organización Mundial del Comercio - OMC (1995) y Día Internacional de la Paz.",
	"2 de Enero":"Inicia Operaciones El Metro de Caracas (1983).",
	"3 de Enero":"Ascenso de Alejandro de Humboldt y Aimé Bonpland al Pico El Ávila (1800).",
	"4 de Enero":"Nace Isaac Newton (1643), Muere Rafael María Baralt (1860), Muere Albert Camus (1960) y Día del Espagueti.",
	"5 de Enero":"Muere José Manuel Díaz Márquez “Joselo” (2013) y Día de la Industria Farmacéutica.",
	"6 de Enero":"Inauguración del Puente de Angostura (1967), Último Capítulo del El Chavo del 8 (1980), Muere Brígido Iriarte (1984), Día de Los Reyes Magos y Día del Deporte.",
	"7 de Enero":"Nace Felipe Baptista (1780), Se descubre La Faja Petrolífera del Orinoco (1936), Nace Juan Gabriel (1950), Muere Juan Rulfo (1986) y Día del Coleccionista.",
	"8 de Enero":"Muere Galileo Galilei (1642), Nace Elvis Presley (1935), Nace Carolina Herrera (1939) y Muere Yvonne De Carlo (2007).",
	"9 de Enero":"Batalla de Clarines (1817) y Día de los Mártires.",
	"10 de Enero":"Muere Ezequiel Zamora (1860), Muere Gabriela Mistral (1957), Día de la Gente Peculiar y Día Mundial de las Aves.",
	"11 de Enero":"Asamblea de Chacachacare (1813) y El Congreso de Angostura por petición de Simón Bolívar Decreta la Abolición Progresiva de la Esclavitud en Venezuela (1820).",
	"12 de Enero":"Nace Juana La Avanzadora (1790), Muere Diego Bautista Urbaneja (1856), Se realiza en Venezuela el Primer Juego Profesional de Béisbol (1946) y Día del Pizzero y Pastelero.",
	"13 de Enero":"Fundación del partido COPEI (1946), Inauguración del Monumento Manto de María Divina Pastora (2016), Muere Diego Rísquez (2018), Día del Artista Nacional y Día Mundial de la Lucha Contra la Depresión.",
	"14 de Enero":"Muere Jesús Soto (2005) y Día de la Divina Pastora.",
	"15 de Enero":"Batalla de Irapa (1813), Nace Martin Luther King (1929), Lanzamiento de Wikipedia (2001), Día del Maestro, Día del Compositor y Día de Martin Luther King Jr.",
	"16 de Enero":"Primera publicación de Don Quijote de la Mancha (1605), Nace José María Cruxent (1911), El Papa Juan Pablo II Declara Venerable al Dr. José Gregorio Hernández (1986), Día Internacional de la Croqueta y Día Internacional de la Comida Picante.",
	"17 de Enero":"Nace Pedro Gual (1783).",
	"18 de Enero":"Nace José Escolástico Andrade Pirela (1782), Muere Ascensión Farreras (1865), Nace Rubén Darío (1867) y Día Internacional de las Legumbres.",
	"19 de Enero":"Muere Juan Vicente Bolívar y Ponte (1786), Fundación de Ciudad Ojeda (1937), Fundación del Movimiento al Socialismo-MAS (1971), Se Inaugura el Parque del Este en Caracas (1961) y Día de las Palomitas de Maíz.",
	"20 de Enero":"Se instala El Congreso Admirable o Congreso Constituyente de Colombia (1830), Día del Pediatra y Día de San Sebastián.",
	"21 de Enero":"Se Funda la Bolsa de Valores de Caracas - BVC (1947), Día Internacional del Abrazo y Festividad de Santa Inés de la Cruz.",
	"22 de Enero":"Muere María Teresa del Toro y Alayza (1803), Nace Luis Level de Goda (1838) y Muere Menca de Leoni (1973).",
	"23 de Enero":"Nace José Francisco Bermúdez (1782), Fin de la dictadura de Marcos Pérez Jiménez (1958), Entra en Vigencia la Constitución de 1961 y Muere Salvador Dalí (1989).",
	"24 de Enero":"Nace Rafael Caldera (1916), No Hit No Run de Urbano Lugo en la final de la LVBP (1987), Día de la Doble Nacionalidad, Día de San Francisco de Sales Patrono de los Periodistas y Ferias Patronales en Honor a la Virgen de la Paz.",
	"25 de Enero":"Nace Manuel Cabré: El Pintor del Ávila (1890).",
	"26 de Enero":"Nace Mariano Picón Salas (1901), Primera Visita del Papa Juan Pablo II (1985), Día Internacional de la Aduana y Día Mundial de la Educación Ambiental.",
	"27 de Enero":"Nace Juan Crisóstomo Falcón (1820), Muere Henri Pittier (1950), Día Internacional de Conmemoración Anual en Memoria de las Víctimas del Holocausto y Día del Nutriólogo.",
	"28 de Enero":"Batalla de Mucuritas (1817), Declaración de la Independencia de Maracaibo (1821), Día de la Zulianidad, Día Nacional del Cine, Día Mundial de la Reducción de las Emisiones de CO2 o Día Mundial de la Acción frente al Calentamiento Terrestre, Día Internacional de la Protección de Datos y Festividad de Santo Tomás de Aquino.",
	"29 de Enero":"Día del Trabajador Social.",
	"30 de Enero":"Nace Juan Antonio Pérez Bonalde (1846), Fundada La Sociedad Venezolana de la Cruz Roja (1895), Muere Mahatma Gandhi (1948), Día del Radio Aficionado, Día del Técnico Electrónico y Día Escolar de la No Violencia y la Paz.",
	"31 de Enero":"Muere José Félix Ribas (1815), Muere Pedro Carujo (1836), Muere Rafael Bolívar Coronado (1924), Muere Oskar Fischinger (1967), Día del Internacionalista, Día Internacional de los Magos y Festividad de San Juan Bosco.",
	"1 de Febrero":"Nace Ezequiel Zamora (1817), Nace Cecilio Acosta (1818) y Día Mundial del Galgo.",
	"2 de Febrero":"Primera Expedición de Miranda (1806), Se crea la Liga Nacional MLB (1876), Se Funda Puerto Ordaz (1952), Día de los Tamales, Día Mundial de los Humedales y Día de la Virgen de La Candelaria.",
	"3 de Febrero":"Nace Mariscal Antonio José de Sucre (1795) y Día Internacional del Abogado.",
	"4 de Febrero":"Nace Francisco de Paula Avendaño (1792), Muere José Manuel Agosto Méndez (1944), Alzamiento militar Contra Carlos Andrés Pérez (1992), Se funda Facebook (2004) y Día Mundial Contra el Cáncer.",
	"5 de Febrero":"Muere Violeta Parra (1967), Nace Cristiano Ronaldo (1985) y Día Internacional de la Nutella.",
	"6 de Febrero":"Toma de las Flecheras (1818), Muere Rubén Darío (1916), Nace Fabricio Ojeda (1929), Nace Bob Marley (1945), Muere Pedro León Zapata (2015) y Día Internacional de Tolerancia Cero con la Mutilación Genital Femenina.",
	"7 de Febrero":"Simón Bolívar es nombrado Jefe Supremo de la Expedición de Los Cayos (1816) y Muere Agustín Codazzi (1859).",
	"8 de Febrero":"Nace Julio Verne (1828) y Muere El Primer Presidente de Venezuela Cristóbal Mendoza (1829).",
	"9 de Febrero":"Muere Carmelo Fernández Páez (1887), Se Funda el Instituto Venezolano de Investigaciones Científicas - IVIC (1959), Muere Julio Jaramillo (1978), Día del Dentista y Festividad de Santa Apolonia.",
	"10 de Febrero":"Se Funda Santa Lucía del Tuy (1621), Simón Bolívar es nombrado Dictador del Perú (1824), Nace Martín Tovar y Tovar (1827), Muere Juan Manuel Cagigal (1856), Nace Guillermo Trujillo Durán (1878) y Se diseña y establece el Escudo Nacional de Venezuela (1954).",
	"11 de Febrero":"Muere el General Carlos Soublette (1870), Jornada Mundial del Enfermo, Día del Antropólogo, Día del Sociólogo, Día Internacional de la Mujer y la Niña en la Ciencia y Festividad de Nuestra Señora de Lourdes.",
	"12 de Febrero":"Francisco de Orellana descubre el Río Amazonas (1542), Fundación de Barcelona (1638), Muere Luis María Rivas Dávila (1814), Batalla de la Victoria (1814), Batalla de Calabozo (1818), Día Mundial Contra la Utilización de Niños y Niñas Soldado, Día Nacional del Nadador y Día de la Juventud.",
	"13 de Febrero":"Creación del Parque Nacional Henri Pittier (1937), Día Nacional del Guardaparques, Día Mundial de la Radio y Día de los Solteros.",
	"14 de Febrero":"Nace Valentín Espinal (1803), Se lanza YouTube (2005), Día de San Valentín, Día del Amor y la Amistad, Día del Telegrafista, Día Mundial de los Sonidos Curativos, Día Mundial de la Cardiopatía Congénita y Día Mundial de la Energía.",
	"15 de Febrero":"Nace Galileo Galilei (1564), Discurso de Angostura (1819) y Día Internacional Contra el Cáncer Infantil.",
	"16 de Febrero":"Batalla de Mata de la Miel (1816), Nace Juan Bautista Dalla-Costa (1823), Muere Alí Primera (1985) y Muere Enrique Hugo Trejo (1998).",
	"17 de Febrero":"Batalla de Coplé (1860), Muere Ignacio Andrade (1925), Acuerdo de Ginebra (1966), Muere Juan Liscano (2001) y Día del Juego Responsable.",
	"18 de Febrero":"Muere Martín Lutero (1546), Muere Miguel Ángel (1564), Nace Humberto Fernández Morán (1924), Se descubre el Planeta Plutón (1930), Día Internacional del Control Biológico, Día Mundial de la Mujer de las Américas y Día Mundial del Síndrome de Asperger.",
	"19 de Febrero":"Inauguración Parcial del Palacio Federal Legislativo (1873), Muere Simón Díaz “El Tío Simón” (2014) y Día Internacional Contra la Homofobia en el Deporte.",
	"20 de Febrero":"El Gobierno se muda desde Angostura hacia la Ciudad de Cúcuta (1821), Muere Francisco de Paula Alcántara (1848), Día de la Federación - Inicio de la Guerra Federal (1859), Nace Juan Vicente Torrealba (1917), Se Inaugura la Sede Propia del Museo de Bellas Artes de Caracas (1938), Muere Vicente Lecuna (1954), Día Internacional del Gato, Día Mundial de la Justicia Social y Día del Camarógrafo.",
	"21 de Febrero":"Nace Roberto Gómez Bolaños - Chespirito (1929), Programa de Febrero de López Contreras (1936), Día Internacional de la Lengua Materna, Día Internacional para la Protección de los Osos y Día Internacional del Guía de Turismo.",
	"22 de Febrero":"Muere Américo Vespucio (1512), Nace Rómulo Betancourt (1908), Nace Alfredo Sadel (1930), Muere Antonio Machado (1939), Día Internacional por la Igualdad Salarial entre Hombres y Mujeres y Día Mundial del Pensamiento Scout.",
	"23 de Febrero":"Muere José María Cruxent (2005), Se funda La Comunidad de Estados Latinoamericanos y Caribeños - CELAC (2010), Día de los Peritos y Día de los Técnicos Industriales.",
	"24 de Febrero":"Se realiza el Primer Sorteo de la Lotería de Caracas (1812), Muere Daniel Florencio O´Leary (1854), Muere Francisco de Paula Avendaño (1870), Nace Alejandro Chataing (1873) y Nace Steve Jobs (1955).",
	"25 de Febrero":"Muere Jacinto Lara (1859), Muere Eneas Perdomo (2011) y Día Internacional del Implante Coclear.",
	"26 de Febrero":"Constitución de la Real Audiencia de Caracas (1787), Muere Félix Soublette (1899), Se Inaugura el Nuevo Circo de Caracas (1919), Muere Manuel Cabré (1984) y Muere Arturo Úslar Pietri (2001).",
	"27 de Febrero":"Batalla Fluvial del Caño Macareo (1812), Muere José Gabriel de Alcalá (1871), Muere José Laurencio Silva (1873), Nace Pedro León Zapata (1929), Se produce el Estallido Social El Caracazo (1989), Muere Wolfgang Larrazábal (2003) y Día Mundial del Trasplante.",
	"28 de Febrero":"Nace José María España (1761), Fundación de San Fernando de Apure (1788), Primera Batalla de San Mateo (1814), Nace Antonio Guzmán Blanco (1829), Muere Simón Rodríguez (1854), Nace Manuel Díaz Rodríguez (1871), Muere Pompeyo Davalillo (2013) y Día Contra las Enfermedades Raras.",
	"1 de Marzo":"Fundación de San Carlos (1678), Muere Juan Manuel Olivares (1797), Nace Arnoldo Gabaldón (1909), Nace Vinicio Adames (1927), Día Contra la Discriminación, Día Mundial del Reciclador de Base, Día Mundial de la Concienciación sobre la Autolesión y Día Internacional de la Protección Civil.",
	"2 de Marzo":"Primer Congreso de Venezuela (1811), La Revolución de Queipa o Grito de Queipa (1898) e Inauguración del Poliedro de Caracas (1974).",
	"3 de Marzo":"Muere Isaac J. Pardo (2000), Día Mundial de la Vida Silvestre, Día Internacional de la Audición y Día Mundial de la Naturaleza.",
	"4 de Marzo":"Muere Arístides Rojas (1894), Muere Ramón Palomares (2016) y Día Mundial del Tenis.",
	"5 de Marzo":"Fundación de Maracay (1701), Revolución de Marzo (1858), Nace Wolfgang Larrazabal (1911), Muere Hugo Chávez (2013), Día del Campesino y Día Mundial de la Eficiencia Energética.",
	"6 de Marzo":"Nace Miguel Ángel (1475), Se funda el Real Madrid C.F. (1902), Nace Gabriel García Márquez (1927), Nace José Manuel Briceño Guerrero (1929) y Muere Gabriel Bracho (1995).",
	"7 de Marzo":"Muere Juana Bolívar Palacios (1847) y Nace Alejandro Otero (1921).",
	"8 de Marzo":"Festividad de San Juan de Dios y Día Internacional de la Mujer.",
	"9 de Marzo":"Nace Américo Vespucio (1454), Muere Mikao Usui (1926), Nace Yuri Gagarin (1934), Se aprueba la Octava Estrella en la Bandera Nacional (2006) y Día Internacional del DJ.",
	"10 de Marzo":"Nace Juan José Landaeta (1780), Nace José María Vargas (1786) y Día del Médico.",
	"11 de Marzo":"Revolución Legalista (1892).",
	"12 de Marzo":"Nace Aldemaro Romero (1928) y Día Mundial Contra el Glaucoma.",
	"13 de Marzo":"Día de La Industria Nacional.",
	"14 de Marzo":"Nace Francisco Lazo Martí (1869), Nace Pedro Elías Gutiérrez (1870), Nace Albert Einstein (1879), Nace Luis Beltrán Prieto Figueroa (1902), Inicia Operaciones Cervecería Polar (1941), Día de las Escuelas de Frontera, Día Nacional del Pescador y El Pescador Artesanal y Día Internacional de Acción Contra las Represas y por los Ríos, el Agua y la Vida.",
	"15 de Marzo":"Nace Juan Bautista Arismendi (1775), Muere Luis Mariano Rivera (2002), El Joropo Venezolano es Declarado Patrimonio Cultural de la Nación (2014), Día Mundial Contra la Matanza de Focas y Día Mundial de los Derechos del Consumidor.",
	"16 de Marzo":"Tercera Batalla de La Puerta o Batalla del Río Sémen (1818) y Muere Renny Ottolina (1978).",
	"17 de Marzo":"Muere Vicente Campo Elías (1814), Día Mundial del Mar y Día de San Patricio.",
	"18 de Marzo":"Creación de la Provincia de Margarita (1525), Muere José Félix Blanco (1872), Se declara el Monumento Natural Cerro María Lionza (1960), Muere Tito Salas (1974), Se declara el Liqui Liqui como Traje Nacional de Venezuela (2017), Día del Comerciante, Día del Negociador Internacional y Día Nacional del Niño Indígena.",
	"19 de Marzo":"Conspiración de Pirela (1799), Nace Caracciolo Parra Pérez (1888), Inauguración del Teatro de la Ópera de Maracay (1973), Día de San José, Día del Carpintero, Día Internacional del Artesano, Día de la Elorzanidad, Día de la Llaneridad y Día del Trabajador Universitario.",
	"20 de Marzo":"Muere Pedro Emilio Coll (1947), Día de la Lengua Francesa, Día Mundial Sin Carne, Día Internacional de la Francofonía, Día Mundial de la Narración Oral, Día Internacional de la Felicidad y Día Mundial del Gorrión.",
	"21 de marzo":"Se funda Twitter (2006), Día Internacional de la Eliminación de la Discriminación Racial, Día Mundial de la Poesía, Día Mundial del Síndrome de Down, Día Internacional de los Bosques, Día Internacional del Color y Día Mundial de la Marioneta o Día Mundial del Títere.",
	"21 al 27 de Marzo":"Semana de Solidaridad con los Pueblos que Luchan Contra el Racismo y la Discriminación Racial.",
	"22 de Marzo":"Día Mundial del Agua.",
	"23 de Marzo":"Nace Vicente Salias (1776), Nace José Antonio Calcaño (1900), Creación de la Sociedad Bolivariana de Venezuela (1938), Día Mundial de la Rehabilitación Motriz y Día Meteorológico Mundial.",
	"24 de Marzo":"Abolición de la Esclavitud en Venezuela (1854), Muere Julio Verne (1905), Día Internacional del Derecho a la Verdad en relación con Violaciones Graves de los Derechos Humanos y de la Dignidad de las Víctimas y Día Mundial Contra la Tuberculosis.",
	"25 de Marzo":"Fundación de Valencia (1555), Muere Antonio Ricaurte (1814), Muere Nicanor Bolet Peraza (1906), Primera Aparición de La Virgen de Betania (1976), Se crea La Fundación Casa del Artista (1987), Muere Rocío Dúrcal (2006), Día Internacional de Solidaridad con los Miembros del Personal Detenidos o Desaparecidos, Día Internacional de Rememoración de las Víctimas de la Esclavitud y la Trata Transatlántica de Esclavos, Día Internacional de los Derechos del Niño por Nacer y Día Internacional de la Vida.",
	"26 de Marzo":"Fundación de La Asunción (1562), Terremoto de Venezuela (1812), Muere Leonardo Infante (1826), Se funda El Mercado Común del Sur - Mercosur (1991), Día Mundial de la Prevención del Cáncer de Cuello Uterino, Día Mundial del Clima y Día Mundial Contra la Epilepsia o Día Púrpura.",
	"27 de Marzo":"Se crea La Provincia de Venezuela (1528), Contrato de los Welser (1528), Se decreta convertir la Iglesia Santísima Trinidad en el Panteón Nacional (1874), Nace Antonio Arraíz (1903), Muere Yuri Gagarin (1968) y Día Internacional del Teatro.",
	"28 de Marzo":"Nace Francisco de Miranda (1750), Se aprueba La Constitución de los Estados Unidos de Venezuela (1864), Creación del Parque Nacional Guatopo (1958), Muere Alberto Arvelo Torrealba (1971) y Día Nacional del Patrimonio Cultural.",
	"29 de Marzo":"Se funda el Real Colegio Seminario de San Buenaventura de Mérida actual Universidad de Los Andes - ULA (1785) y Muere la Negra Matea (1886).",
	"30 de Marzo":"Nace Vincent van Gogh (1853), Tratado de Paz y Amistad entre Venezuela y España (Reconocimiento de la Independencia de Venezuela por España 1845), Muere Pedro Emilio Coll (1947), Día Internacional de la Trabajadora del Hogar y Día Mundial Contra el Trastorno Bipolar.",
	"31 de Marzo":"Se funda San Cristóbal (1561), Muere Isaac Newton (1727), Batalla de Bocachica (1814), Expedición de los Cayos (1816), Se Promulga la Ley de Monedas que establece el Bolívar de Plata como Unidad Monetaria (1879), Día Mundial Contra el Cáncer de Colon, Día Internacional de la Visibilidad Transgénero, Día del Documento Libre y Día Mundial de la Copia de Seguridad o Backup.",
	"1 de Abril":"Se funda el Diario El Universal (1909), Se funda Apple (1976), Decreto que Prohíbe la Publicidad de Tabaco en la Radio (1981), Día Internacional de la Diversión en el Trabajo y Día Mundial de la Educación.",
	"2 de Abril":"Nace Ana María de Campos (1796), Batalla de las Queseras del Medio (1819), Muere Juan Pablo II (2005), Día Mundial de la Concientización sobre el Autismo y Día Internacional del Libro Infantil y Juvenil.",
	"3 de Abril":"Día Internacional del Teléfono Móvil.",
	"4 de Abril":"Nace Alirio Rodríguez (1934), Muere Martin Luther King (1968), Se funda Microsoft (1975) y Día Internacional de Información sobre el Peligro de las Minas y de Asistencia para las Actividades Relativas a las Minas.",
	"5 de Abril":"Muere Rómulo Gallegos (1969) y Festividad de San Vicente Ferrer.",
	"6 de Abril":"Primeros Juegos Olímpicos Modernos (1896), Primera Edición de El Principito (1943), Se Inaugura el Palacio de las Academias (1956), Día Internacional del Deporte para el Desarrollo y la Paz, Día Mundial de la Actividad Física y Día del Interno de Medicina.",
	"7 de Abril":"Batalla de Bomboná (1822), Sublevación del Movimiento Estudiantil Contra Juan Vicente Gómez (1928), Se funda La Organización Mundial de la Salud - OMS (1948), Día Mundial de la Salud y Día Internacional de Reflexión sobre el Genocidio cometido en Rwanda.",
	"8 de Abril":"Se funda La Colonia Tovar (1843), Se crea La Academia Nacional de Medicina de Venezuela (1904) y Muere Pablo Picasso (1973).",
	"9 de Abril":"Convención de Ocaña (1826), Muere Tomás de Heres (1842), Muere Fernando Gómez de Saa (1879) y Nace Magdalena Sánchez (1915).",
	"10 de Abril":"Se crea La Provincia de Portuguesa (1851), Se funda La Academia Venezolana de la Lengua (1883), Muere Lisandro Alvarado (1929), Día del Asistente Dental, Día del Investigador Científico, Día Internacional de la Homeopatía y Día Mundial de la Ciencia y la Tecnología.",
	"11 de Abril":"Segunda Batalla de Maturín (1813), Batalla de San Félix (1817), Nace Fernando Paz Castillo (1893), Nace Conny Méndez (1898), Se funda La Organización Internacional del Trabajo - OIT (1919), Golpe de Estado (2002), Día Mundial Contra el Parkinson, Día Internacional del Remero y Día Internacional del Juego de Mesa.",
	"12 de Abril":"Nace Juan Manuel Olivares (1760), Se descubre El Primer Yacimiento Petrolero en Venezuela (1875), Yuri Gagarin se convierte en la primera persona en viajar al espacio exterior (1961), Día del Obstetra, Día Internacional de los Vuelos Espaciales Tripulados, Día Mundial Contra la Contaminación Acústica, Día Mundial de Reducción de Gastos Militares y Día del Decorador y Vidrierista.",
	"13 de Abril":"Nace Francisco Linares Alcántara (1825), Declarado Monumento Histórico Nacional El Castillo Negro (1976), Muere Eduardo Galeano (2015), Día de la Milicia Nacional Bolivariana del Pueblo en Armas y de la Revolución de Abril y Día Internacional del Beso.",
	"14 de Abril":"Se decreta El Parque Nacional Terepaima (1976), Día del Panamericano, Día de las Américas, Día Internacional de la Lucha Contra el Chagas y Día Internacional del Arquero.",
	"15 de Abril":"Nace Leonardo da Vinci (1452), Muere César Vallejo (1938), Muere Pedro Infante (1957), Día Mundial del Ciclista y Día Mundial del Arte.",
	"16 de Abril":"Nace Francisco Espejo (1758), Batalla de Arao (1814), Nace Charles Chaplin (1889), Muere Joaquín Crespo (1898), Muere Alejandro Chataing (1928), Día Mundial de la Voz y Día Mundial Contra la Esclavitud Infantil.",
	"17 de Abril":"Sublevación de Juan Francisco León (1749), Debuta Luis Aparicio en la MLB (1956), Muere Gabriel García Márquez (2014), Día del Joven Explorador, Día Mundial Contra la Hemofilia, Día de la Unión de Naciones Suramericanas (Unasur) y Día Internacional de la Lucha Campesina.",
	"18 de Abril":"Creado y Legislado el Escudo de Venezuela (1836), Muere José Rafael Pocaterra (1955), Muere Albert Einstein (1955), Muere Antonio Lauro (1986), Día de la Ciudadanía, Día Internacional de los Monumentos y Sitios y Día Mundial del Radioaficionado.",
	"19 de Abril":"Proclamación de la Independencia de Venezuela (1810), Inauguración del Archivo General de La Nación (1911), Inauguración del Teatro Teresa Carreño (1983), Día de la Municipalidad, Día Mundial de la Bicicleta y Día del Aborigen Americano.",
	"20 de Abril":"Muere Rafael Arévalo González (1935), Se declarada Monumento Histórico Nacional La Cuadra de Bolívar (1959), Muere Mario Moreno Cantinflas (1993) y Día de la Lengua China en las Naciones Unidas.",
	"21 de Abril":"Nace Anselmo Belloso Rodríguez (1805) y Día Mundial de la Creatividad y de la Innovación.",
	"22 de Abril":"Muere Miguel de Cervantes (1616), Se lanza la Primera Computadora de Escritorio producida Comercialmente ”Programma 101” (1964) y Día de La Tierra.",
	"23 de Abril":"Francisco de Miranda es nombrado Generalísimo (1812), Muere Teresa de la Parra (1936), Día Mundial del Libro y del Derecho de Autor, Día de la Lengua Inglesa, Día del Idioma Español y Día Internacional de la Cerveza.",
	"24 de Abril":"La Acción de Juana de Ávila (1822), Tratado o Convenio de Coche (1863), Día Mundial Contra la Meningitis y Día del Caficultor.",
	"25 de Abril":"Nace José Leonardo Chirino (1754), Nace Rafael Rangel (1877), Guerra Hispano-Estadounidense (1898), Nace Marcos Pérez Jiménez (1914), Muere Aquiles Nazoa (1976), Día del Bioanalista, Día Mundial Contra el Paludismo, Día del ADN, Día Internacional Contra el Maltrato Infantil y Día Mundial de los Pingüinos.",
	"26 de Abril":"Nace Raúl Leoni (1905), Nace Cleto Rojas (1928), Día Internacional del Humor, Día Mundial de la Propiedad Intelectual y Día de la Visibilidad Lésbica.",
	"27 de Abril":"Simón Bolívar renuncia a la Presidencia (1830), Día del Código Morse, Día Mundial del Diseñador Gráfico y Día Mundial del Diseño.",
	"28 de Abril":"Nace Manuel Carlos Piar (1774), Nace Pompeyo Márquez (1922), Día del Sacerdote, Día Internacional de la Seguridad y Salud en el Trabajo, Día de la Industria Nacional del Hierro y el Petróleo y Día del Bacteriólogo.",
	"29 de Abril":"Nace Antonio Nicolás Briceño (1782), Muere Juan Crisóstomo Falcón (1870), Nace Luis Aparicio (1934), Día Nacional de la Ética Ciudadana, Día Internacional de la Danza y Día de Conmemoración de todas las Víctimas de la Guerra Química.",
	"30 de Abril":"Revolución de los Morrocoyes o Cosiata (1826), Muere Adolf Hitler (1945), Es declarado Monumento Histórico Nacional El Fortín El Salto (1976), El CERN libera al público la tecnología World Wide Web (1993) y Día Internacional del Jazz.",
	"1 de Mayo":"Día del Trabajador.",
	"2 de Mayo":"Muere Leonardo da Vinci (1519), Combate Naval de Los Frailes (1816), Nace Atanasio Girardot (1791), Se crea el Parque Nacional Sierra Nevada (1952) y Día Internacional Contra el Acoso Escolar o Día Contra el Bullying.",
	"3 de Mayo":"Fundación de Santa Cruz Primera Ciudad de Venezuela (1502), Nace José de la Cruz Carrillo (1788), Día del Albañil, Día de la Cruz de Mayo, Día Mundial de la Libertad de Prensa y Día Internacional del Rap.",
	"4 de Mayo":"Nace José Gregorio Monagas (1795), Nace Ana Enriqueta Terán (1918), Nace Luis Herrera Campins (1925), El Carupanazo Insurrección Militar de Izquierda (1962), Se crea La Fundación Cinemateca Nacional de Venezuela (1966), Día Internacional del Combatiente de Incendios Forestales y Día de Star Wars o de La Guerra de las Galaxias.",
	"5 de Mayo":"Muere Napoleón Bonaparte (1821), Nace Eleazar López Contreras (1883), Muere Billo Frómeta (1988), Día Internacional de la Partera, Día Internacional del Celíaco, Día del Patrimonio Mundial Africano y Día Mundial de la Higiene de las Manos.",
	"6 de Mayo":"Simón Bolívar es proclamado “Jefe Supremo de la República y sus Ejércitos” (1816), Congreso de Valencia (1830), Muere Pedro Gual (1862), Muere José Antonio Páez (1873), Día Internacional Contra la Osteogénesis Imperfecta, Día del Reportero Gráfico y Día Internacional Sin Dietas.",
	"7 de Mayo":"Muere Fernando Peñalver (1837), Nace Ramón Palomares (1935), Nace José Antonio Abreu (1939) y Se funda Los Leones del Caracas (1942).",
	"8 de Mayo":"Muere José María España (1799), Congresillo de Cariaco (1817), Muere Manuel Palacio Fajardo (1819), Nace Tito Salas (1887), Nace Sofía Ímber (1924), Se funda La Organización de los Estados Americanos - OEA (1948), Día del Entrenador Deportivo, Día Mundial Contra el Cáncer de Ovario y Día Internacional de la Cruz Roja.",
	"9 de Mayo":"Nace Ferdinand Monoyer (1836), Nace Ricardo Aguirre (1939), Se crea la Fundación Instituto Jardín Botánico (1991) y Día de la Victoria sobre el Nazismo.",
	"10 de Mayo":"Movimiento de José Leonardo Chirinos (1795), Muere Francisco Rodríguez del Toro (1851), Nace Armando Reverón (1889), Día Mundial Contra el Lupus, Día del Artista Plástico y Día de la Afrovenezolanidad.",
	"11 de Mayo":"Se firma el Tratado de Antímano (1868) y Muere Bob Marley (1981).",
	"12 de Mayo":"Nace Florence Nightingale (1820), Muere Jacinto Convit (2014), Día Internacional de las Enfermeras, Día Internacional Contra la Fibromialgia, Día del Comunicólogo y Día Escolar de las Matemáticas.",
	"12 al 23 de Mayo":"Foro Permanente para las Cuestiones Indígenas de la ONU.",
	"13 de Mayo":"Muere Salvador Garmendia (2001) y Festividad de La Virgen de Fátima.",
	"14 de Mayo":"Se inicia la Campaña Admirable (1813), Nace César Rengifo (1915), Muere Luis Razetti (1932) y Muere María Luisa Escobar (1985).",
	"15 de Mayo":"Día del Compositor, Día Internacional de la Familia, Día Internacional de la Objeción de Conciencia y Día de San Isidro Labrador.",
	"16 de Mayo":"Nace Juana Bolívar Palacios (1779), Nace Arturo Uslar Pietri (1906) y Nace Juan Rulfo (1917).",
	"17 de Mayo":"Nace Federico Brandt (1878), Nace Aquiles Nazoa (1920), Muere Mario Benedetti (2009), Día Internacional Contra la Homofobia y la Transfobia, Día Mundial Contra la Hipertensión, Día Mundial de las Telecomunicaciones y la Sociedad de la Información, Día Mundial de Internet y Día Internacional del Reciclaje.",
	"18 de Mayo":"Nace Josefa Camejo (1791), Nace Juan Pablo II (1920), Declarado Parque Nacional El Junquito (1975), Día Internacional de los Museos y Día Internacional de la Fascinación por las Plantas.",
	"19 de Mayo":"Muere Emilio Arévalo Cedeño (1965), Día Mundial del Médico de Familia, Día Mundial Contra la Enfermedad Inflamatoria Intestinal y Día Mundial de la Donación de Leche Humana.",
	"20 de Mayo":"Muere El Almirante Cristóbal Colón (1506), Nace Enrique Bernardo Núñez (1895), Día de la Radio en Venezuela, Día del Publicista, Día Nacional del Cronista y Día Mundial de la Metrología.",
	"21 de Mayo":"Nace Emilio Boggio (1857), Se Incorpora Venezuela a la Cruz Roja Internacional (1894), Se funda la FIFA (1904), Muere Andrés Eloy Blanco (1955), Se Declara Parque Nacional Cueva de la Quebrada del Toro (1969), Sale el juego Pac-Man (1980), Día Internacional del Scratch, Día de la Salud Visual, Día del Optometrista y Día Mundial de la Diversidad Cultural para el Diálogo y el Desarrollo.",
	"22 de Mayo":"Se funda Ciudad Bolívar (1764), Ratificación del Tratado de Coche (1863) y Día Internacional de la Diversidad Biológica.",
	"23 de Mayo":"Revolución Liberal Restauradora o la Invasión de los 60 (1899), Declarada La Orquídea como Flor Nacional (1951), Declarado El Turpial como Ave Nacional (1958), Día Mundial Contra el Melanoma, Día Internacional para la Erradicación de la Fístula Obstétrica, Día Mundial de la Tortuga y Día Internacional del Primer Beso.",
	"24 de Mayo":"Batalla de Pichincha (1822), Día del Telegrafista, Día Internacional de Las Mujeres por La Paz y El Desarme y Festividad de María Auxiliadora.",
	"25 de Mayo":"Fundación de Barinas (1577), Es adoptado el “Gloria al Bravo Pueblo” como Himno Nacional de Venezuela (1881), Nace Gabriel Bracho (1915), Día de África y Día Internacional de los Niños Desaparecidos.",
	"26 de Mayo":"Matrimonio de Simón Bolívar (1802) y Decretado Parque Nacional Morrocoy (1974).",
	"27 de Mayo":"Nace Jaime Lusinchi (1924) y Nace Juan Germán Roscio (1763).",
	"28 de Mayo":"Nace Jacinto Lara (1778), Nace Juan Vicente González (1810), Primera Batalla de Carabobo (1814), Día Internacional del Juego, Día Internacional de Acción por la Salud de las Mujeres, Día Internacional de la Higiene Menstrual, Día de la Hamburguesa y Día Mundial de la Nutrición.",
	"29 de Mayo":"Se Inaugura la Primera Línea Telegráfica en Venezuela (1856), Declarado el Araguaney como Árbol Nacional (1948), Día del Trabajador Tribunalicio, Día Internacional del Everest, Día Mundial de la Salud Digestiva (DMSD), Día del Anciano, Día Nacional del Adulto Mayor y Día Internacional del Personal de Paz de las Naciones Unidas.",
	"30 de Mayo":"Nace Carlos Raúl Villanueva (1900), Día del Geógrafo y Festividad de Santa Juana de Arco.",
	"31 de Mayo":"Muere Pedro Elías Gutiérrez (1954), Nace Tulio Febres Cordero (1860), Muere Zaha Hadid (2016), Día Internacional del Tripulante de Cabina o Auxiliar de Vuelo, Día Mundial de No Fumar y Visitación de la Virgen María.",
	"1 de Junio":"Se inicia Oficialmente las Transmisiones a Color en la Televisión Venezolana (1980), Día Internacional de la Leche, Día Mundial de las Madres y los Padres y Día Internacional de la Infancia.",
	"2 de Junio":"Muere Luisa Cáceres de Arismendi (1866), Nace Vicente Gerbasi (1913), El Porteñazo Conspiración Cívico-Militar (1962), Día Mundial de la Lucha Contra la Miastenia.",
	"3 de Junio":"Muere Tulio Febres Cordero (1938) y Día del Profesional de Recursos Humanos.",
	"4 de Junio":"Fallece Antonio José de Sucre (1830), Nace Nicanor Bolet Peraza (1838), Día Internacional de la Fertilidad, Día del Optometrista en Venezuela y Día Internacional de los Niños Víctimas Inocentes de Agresión.",
	"5 de Junio":"Nace Jesús Soto (1923), Muere Eugenio Montejo (2008) y Día Internacional del Medio Ambiente.",
	"6 de Junio":"Nace Rafael Bolívar Coronado (1884), Muere Anselmo Belloso Rodríguez (1885), Sale el juego Tetris (1984), Día de la Lengua Rusa, Día Mundial del YoYo, Día de la Radiodifusión y Día Mundial del Paciente Trasplantado.",
	"7 de Junio":"Muere Emilio Boggio (1920) y Nace Eladio Tarife (1931).",
	"8 de Junio":"Muere Francisco María Faría (1838), Día Mundial de los Océanos y Día Mundial del Terapista del Lenguaje.",
	"9 de Junio":"Nace José Antonio Ramos Sucre (1890), Muere Adam West (2017), Día Internacional de los Archivos y Día del Embajador Estudiantil.",
	"10 de Junio":"Nace Antonio Ricaurte (1786), Nace Brígido Iriarte (1921), Día Internacional de la Heráldica y Día Mundial de la Seguridad Vial.",
	"11 de Junio":"Inauguración del Teatro Nacional (1905), Nace Salvador Garmendia (1928) y Muere José Luis Armenteros (2016).",
	"12 de Junio":"Se crea la Real Casa de Moneda de Caracas (1802), Nace (1805) y Muere (1875) Julián Castro, Batalla de Cantaura (1819), Muere Teresa Carreño (1917), Creación del Parque Nacional Canaima (1962), Día Internacional del Doblaje, Día Mundial Contra el Trabajo Infantil y Festividad de San Onofre.",
	"13 de Junio":"Nace José Antonio Páez (1790), Nace Pedro Centeno Vallenilla (1904), Muere José Antonio Ramos Sucre (1930), Día Mundial Contra el Cáncer de Piel, Día de San Antonio de Padua, Día del Tamunangue Larense y Día Internacional de Sensibilización sobre el Albinismo.",
	"14 de Junio":"Día Mundial del Pepino y Día Mundial del Donante de Sangre.",
	"15 de Junio":"Proclama de Guerra a Muerte (1813), Muere Antonio Nicolás Briceño (1813), Muere José Gil Fortoul (1943), Se funda la UEFA (1954), Día Global del Viento y Día Mundial de Toma de Conciencia de Abuso y Maltrato en la Vejez.",
	"16 de Junio":"Nace José Gabriel de Alcalá (1776), Nace Arturo Michelena (1863), Nace Alfredo Boulton (1908), Primer Vuelo de una Mujer al Espacio Exterior Valentina Tereshkovade (1963), Se inaugura La Cuadra de Bolívar (1963), Día Internacional de las Remesas Familiares, Día Internacional del Niño Africano y Día Mundial de las Tortugas Marinas.",
	"17 de Junio":"Nace Rufino Blanco Fombona (1874) y Día Mundial de Lucha Contra la Desertificación y la Sequía.",
	"18 de Junio":"Nace Andrés Galarraga (1961), Se firma el Protocolo de Puerto España (1970), Decretado Monumento Natural La Laguna de Urao (1979), Día Mundial Contra la Incineración de Residuos, Día del Orgullo Autista y Día Internacional del Sushi.",
	"19 de Junio":"El Gobierno Nacional Adquiere Miraflores (1911), Día Mundial de la Lucha Contra la Drepanocitosis y Día para la Eliminación de la Violencia Sexual en los Conflictos.",
	"20 de Junio":"Primer Capítulo del El Chavo del 8 (1971) y Día Mundial de los Refugiados.",
	"21 de Junio":"Muere Fabricio Ojeda (1966), Muere Pompeyo Márquez (2017), Fiesta de la Música, Día Mundial Contra la Esclerosis Lateral Amiotrófica (ELA), Día Internacional del Sol, Día del Apicultor, Día Mundial de la Patineta, Día Internacional del Yoga, Día de la Marina Mercante en Venezuela, Día Mundial de la Hidrografía y Día Internacional del Selfie.",
	"22 de Junio":"Instalación del Congreso de Panamá (1826), Muere Juan Bautista Arismendi (1841), Nace Oskar Fischinger (1900), Día Internacional del Escarabajo de Volkswagen y Día Mundial del Suelo y la Tierra Fértil.",
	"23 de Junio":"Nace Cristóbal Mendoza (1772) Primer Presidente de Venezuela, Nace Pancho Villa (1878), Día del Abogado, Día de las Naciones Unidas para la Administración Pública, Día Internacional de las Viudas y Día Olímpico.",
	"24 de Junio":"Batalla de Carabobo (1821), Muere Pedro Camejo “Negro Primero” (1821), Nace Lionel Messi (1987), Muere Ramón José Velásquez Mujica (2014), Día del Ejército Bolivariano, Día del Maquillador, Día Internacional del Socorrista, Día Internacional Contra la Contaminación Electromagnética y Día de San Juan Bautista.",
	"25 de Junio":"Nace Pedro León Torres (1788), Muere Héctor Poleo (1989), Muere Michael Jackson (2009), Día de la Gente de Mar y Día Mundial contra el Vitíligo.",
	"26 de Junio":"Nace Salvador Allende (1908), Nace José Luis Armenteros (1943), El Barcelonazo - Rebelión Militar (1961), Día Internacional en Apoyo de las Víctimas de la Tortura, Día Internacional de la Lucha Contra el Uso Indebido y el Tráfico Ilícito de Drogas y Día Internacional de la Preservación de los Bosques Tropicales.",
	"27 de Junio":"Se funda El Correo del Orinoco (1818), Guzmán Blanco Decreta la Instrucción Pública Gratuita y Obligatoria para todos los Venezolanos (1870), Día Internacional de la PyME y Día Nacional del Periodista.",
	"28 de Junio":"Nace Leonardo Infante (1798), Muere Jesús Enrique Lossada (1948), Muere Alfredo Sadel (1989), Día Nacional del Teatro.",
	"29 de Junio":"Nace Antoine de Saint-Exupéry (1900) Autor de la Obra “El Principito”, Muere José Gregorio Hernández (1919), Se lanza el primer iPhone iOS 1.0 (2007), Muere Inocente Carreño (2016), Día Mundial del Diseño Industrial, Día Mundial Contra la Esclerodermia y Día de la Parranda de San Pedro.",
	"30 de Junio":"Nace Carmelo Fernández Páez (1809), Laudo Arbitral donde se Ratifica la Soberanía de Venezuela sobre Isla de Aves (1865), Nace Pompeyo Davalillo (1931), Día Internacional del Asteroide, Día Mundial de las Redes Sociales y Día Internacional del Decorador y el Diseñador.",
	"1 de Julio":"Proclamado los Derechos del Pueblo (1811), Día Internacional del Chiste, Día Internacional del Reggae, Día del Vigilante de Tránsito y Día Mundial del Becario.",
	"2 de Julio":"Batalla de Niquitao (1813), Muere Felipe Pirela (1972), Día Mundial de los Ovnis, Día del Editor de Revistas y Día Internacional del Periodista Deportivo.",
	"3 de Julio":"Nace Rafael María Baralt (1810) y Día Internacional Sin Bolsas Plásticas.",
	"4 de Julio":"Muere Marie Curie (1934), Se funda La Comunidad del Caribe - CARICOM (1973), Día del Arquitecto, Día Internacional de la Vida Silvestre y Día de la Constitución Ambiental.",
	"5 de Julio":"Firma del Acta de la Independencia de Venezuela (1811), Muere Alirio Díaz (2016) y Día Mundial del Bikini.",
	"6 de Julio":"Nace Luis Brión (1782), Nace Isaías Medina Angarita (1897), Reforma del Código Civil (1982) y Muere Monseñor Ignacio Cardenal Velasco (2003).",
	"7 de Julio":"Fundada Villa de Upata (1762), Nace Juan Liscano (1915), Día Mundial de la Conservación del Suelo y Día Mundial Contra el Síndrome de RubinsteinTaybi.",
	"8 de Julio":"Muere Cecilio Acosta (1881), Muere José Humberto Quintero (1984) y Día Mundial Contra la Alergia.",
	"9 de Julio":"Nace Juan Manuel Agosto Méndez (1871), Se funda la Conmebol (1916), Nace Mercedes Sosa (1935) y Día Internacional de la Destrucción de Armas de Fuego.",
	"10 de Julio":"Nace Antonio Ricaurte (1786), Nace Argelia Laya (1926) y Muere Francisco Antonio Rísquez (1941).",
	"11 de Julio":"Nace Juan Lovera “El Pintor de los Próceres” (1776), Muere Ferdinand Monoyer (1912), Nace Eneas Perdomo (1930) y Día Mundial de la Población.",
	"12 de Julio":"Nace Agustín Codazzi (1793), Nace Pedro Emilio Coll (1872) y Nace Pablo Neruda (1904).",
	"13 de Julio":"Creación de la Biblioteca Nacional de Venezuela - BNV (1833), Muere José María Vargas (1854), Día Internacional del Director de Orquesta, Día Mundial del Rock y Día Internacional del Trastorno por Déficit de Atención e Hiperactividad.",
	"14 de Julio":"Muere Francisco de Miranda (1816).",
	"15 de Julio":"Se Inaugura La Iglesia de La Santísima Trinidad en Caracas (1781), Muere Francisco Espejo (1814), Nace Jesús Enrique Lossada (1892), Nace Argimiro Gabaldón (1919) y Día Mundial de las Habilidades de la Juventud.",
	"16 de Julio":"Muere Celia Cruz (2003), Día de la Virgen del Carmen, Día del Defensor Público y Día Nacional del Policía.",
	"17 de Julio":"Nace José Ignacio Cabrujas (1937).",
	"18 de Julio":"Nace Nelson Mandela (1918), Se funda La Universidad Simón Bolívar - USB (1967), Día Internacional de Nelson Mandela y Día Mundial de la Escucha.",
	"19 de Julio":"Nace Juan José Flores (1800).",
	"20 de Julio":"Nace Héctor Guillermo Villalobos (1911), Muere Pancho Villa (1923), Llegada del Hombre a la Luna (1969) y Día del Amigo.",
	"21 de Julio":"Día del Médico Veterinario.",
	"22 de Julio":"Batalla de Los Horcones (1813), Día Mundial Contra la Megaminería, Día Mundial del Cerebro, Día Internacional del Trabajo Doméstico y Festividad de Santa María Magdalena.",
	"23 de Julio":"Se promulga la Primera Ley del Trabajo en Venezuela (1928).",
	"24 de Julio":"Nace El Libertador Simón Bolívar (1783), Batalla Naval del Lago de Maracaibo (1823), Nace Juan Vicente Gómez (1857), Día de la Armada Venezolana y Día Mundial del Autocuidado de la Salud.",
	"25 de julio":"Fundación de Caracas (1567), Nace Santiago Mariño (1788), Batalla del Pantano de Vargas (1819), Muere Federico Brandt (1932), Se declara Monumento Nacional La Casa Natal del Libertador Simón Bolívar (2002) y Día Internacional de la Mujer Afrodescendiente.",
	"26 de Julio":"Fundación de la Ciudad de Coro (1527), Nace Antonio Machado (1875), Día Internacional para la Defensa del Ecosistema Manglar y Día del Abuelo.",
	"27 de Julio":"Día del Bibliotecólogo y Archivólogo, Día Internacional del Perro Callejero y Día Mundial para la Prevención de Enfermedades de la Cabeza y el Cuello.",
	"28 de Julio":"Muere Antonio Guzmán Blanco (1899), Nace Carlos Moreán (1947), Nace Hugo Rafael Chávez Frías (1954) y Día Mundial Contra la Hepatitis.",
	"29 de Julio":"Se Inaugura el Arco de Triunfo de París (1836), Muere Vincent van Gogh (1890), Muere Arturo Michelena (1898), Se crea la Radiodifusora Nacional de Venezuela actualmente Radio Nacional de Venezuela - RNV (1936), Se funda la NASA (1958), Terremoto de Caracas (1967) y Día Internacional del Tigre.",
	"30 de Julio":"Muere Fernando Paz Castillo (1981), Día Internacional de la Amistad y Día Mundial Contra la Trata de Personas.",
	"31 de Julio":"La Batalla de Matasiete (1817), Muere Antoine de Saint-Exupéry (1944) Autor de la Obra “El Principito”, Día Internacional del Orgasmo y Festividad de San Ignacio de Loyola.",
	"1 de Agosto":"Inicia Transmisiones VTV (1964), Día de la Pachamama y Día Mundial de la Alegría.",
	"1 al 7 de Agosto":"Semana Mundial de la Lactancia Materna.",
	"2 de Agosto":"Nace José Ángel Lamas (1775), Nace Rómulo Gallegos (1884) y Cristóbal Colón llega a Venezuela (1498).",
	"3 de Agosto":"Batalla Naval de Cumaná (1813), Nace Antonio Lauro (1917), Se funda el Diario El Nacional (1943), Día de la Bandera Nacional y Día Internacional de la Planificación Familiar.",
	"4 de Agosto":"Día de la Guardia Nacional Bolivariana fundada en 1937 por el Presidente de la República General en Jefe (Ej) Eleazar López Contreras y Festividad de San Juan María Vianney.",
	"5 de Agosto":"Abandona Venezuela el último Oficial al Servicio del Rey de España (1823), Se tiende el Primer Cable Transatlántico Submarino (1858), Nace Neil Armstrong (1930) y Se Inaugura el Museo de los Niños de Caracas (1982).",
	"6 de Agosto":"Batalla de Junín (1824), Creación de Bolivia (1825), Nace Andrés Eloy Blanco (1896), Festividad del Santo Cristo de la Grita y Día del Aliento Fresco.",
	"7 de Agosto":"Batalla de Boyacá (1819) y Muere Rosario Castellanos (1974).",
	"8 de Agosto":"Fundación del Ateneo de Caracas (1931), Nace Simón Díaz “El Tío Simón” (1928) y Día del Orgasmo Femenino.",
	"9 de Agosto":"Día Internacional de los Pueblos Indígenas y Día Internacional de la Solidaridad con la Lucha de la Mujer en Sudáfrica y Namibia.",
	"10 de Agosto":"Nace Juan Manuel Cajigal (1803) y Día Mundial del León.",
	"11 de Agosto":"Se publica la 1era edición de Doña Bárbara (1929), Se Inaugura La Plaza Francia o Plaza Altamira (1945), Muere Vicente Emilio Sojo (1974) y Día Mundial del Hip Hop.",
	"12 de Agosto":"Termina la Guerra Hispano-Estadounidense (1898), Nace Mario Moreno Cantinflas (1911), Día Internacional de la Juventud, Día Internacional del Disco de Vinilo y Día Mundial del Elefante.",
	"13 de Agosto":"Nace Henri Pittier (1857), Muere Alejandro Otero (1990), Día Internacional del Zurdo, Día Internacional del Filósofo y Día Mundial del Clarinetista.",
	"14 de Agosto":"Muere Pedro Centeno Vallenilla (1988).",
	"15 de Agosto":"Nace Napoleón Bonaparte (1769), Juramento de Simón Bolívar en el Monte Sacro en Roma (1805), Nace Mikao Usui (1865), Se inaugura oficialmente el Canal de Panamá (1914), Día Mundial de la Relajación, Día Mundial del Reiki, Festividad de la Virgen de La Consolación de Táriba y Día de la Asunción de María.",
	"16 de Agosto":"Muere Carlos Raúl Villanueva (1975), y Muere Elvis Presley (1977).",
	"17 de Agosto":"Muere Wenceslao Urrutia (1869), Se estrena el Primer Dibujo Animado de la Historia - Fantasmagorie (1908), Nace Carlos Cruz Diez (1923) y Día Internacional del Peatón.",
	"18 de Agosto":"Muere Aníbal Nazoa (2001) y Muere Magdalena Sánchez (2005).",
	"19 de Agosto":"Nace Luis María Rivas Dávila (1778), Nace Luis Mariano Rivera (1906), Día Mundial de la Asistencia Humanitaria, Día Mundial del Fotógrafo y Día Mundial de la Fotografía.",
	"20 de Agosto":"Muere Rafael Rangel (1909), Nace Héctor Poleo (1918) y Día Nacional del Bombero.",
	"21 de Agosto":"Nace Stephen Hillenburg (1961) creador de Bob Esponja.",
	"22 de Agosto":"Muere Pedro León Torres (1822), Nace Joaquín Crespo (1841) y Día del Folklore.",
	"23 de Agosto":"Muere Juan José Rondón (1823), Muere Rafael Urdaneta (1845), Día Europeo de Conmemoración de las Víctimas del Estalinismo y el Nazismo, Día Internacional del Recuerdo de la Trata de Esclavos y de su Abolición y Día Internacional del Internauta.",
	"24 de Agosto":"Descubrimiento del Lago de Maracaibo (1499), Nace Bartolina Sisa (1750), Nace Bartolomé Salom (1780) y Día Internacional de los Parques Naturales.",
	"25 de Agosto":"Se inaugura el Museo de Arte Moderno Jesús Soto (1973), Muere Truman Capote (1984), Se lanza la Primera Versión de Linux 0.01 (1991) y Día del Peluquero.",
	"26 de Agosto":"Muere Anton van Leeuwenhoek (1723), Nace Teresa de Calcuta (1910), Día del Licenciado en Administración, Día del Actor, Día Internacional Contra el Dengue y Día Internacional del Perro.",
	"27 de Agosto":"Día Internacional de Cosplay y Natalicio del Capitan de Maestranzas Manuel Toro (1765).",
	"28 de Agosto":"Muere Miguel Otero Silva (1985) y Muere Juan Gabriel (2016).",
	"29 de Agosto":"Nace Laudelino Mejías (1893), Nace Michael Jackson (1958), Nacionalización del Petróleo (1975), Día Internacional Contra los Ensayos Nucleares, Día Internacional del Cartero y Día Internacional del Gamer.",
	"30 de Agosto":"Día Internacional de las Víctimas de Desapariciones Forzadas y Festividad de Santa Rosa de Lima.",
	"31 de Agosto":"Muere Lucila Palacios (1994), Día Mundial de la Solidaridad, Día de la Obstetricia y de la Embarazada y Festividad de San Ramón Nonato.",
	"1 de Septiembre":"Nace José Miguel Sánz (1756), Nace Yvonne De Carlo (1922), Muere Arnoldo Gabaldón (1990) y Día Mundial de Oración por El Medioambiente.",
	"2 de Septiembre":"Fundación del Banco de Venezuela (1890), Fin de la Segunda Guerra Mundial (1945) y Día de la Industria.",
	"3 de Septiembre":"Fundación de la Academia Militar de Venezuela (1810), Nace Eduardo Galeano (1940), Muere Vinicio Adames (1976) y Día Mundial de la Higiene.",
	"4 de Septiembre":"Muere Santiago Mariño (1854), Nace Alberto Arvelo Torrealba (1905), Nace Felipe Pírela (1941), Se funda Google (1998), Se declara Santa a la Madre Teresa de Calcuta (2016), Día del Empleado Público, Día Internacional del Taekwondo y Día Mundial de la Salud Sexual.",
	"5 de Septiembre":"Muere Bartolina Sisa (1782), Muere Teresa de Calcuta (1997), Día Internacional de la Beneficencia, Día de la Mujer Indígena, Día Mundial Contra el Mieloma Múltiple y Día Mundial de los Scouts.",
	"6 de Septiembre":"La Carta de Jamaica (1815), Día Internacional del Sexo y Día Mundial de las Aves Playeras.",
	"7 de Septiembre":"Nace José Laurencio Silva (1791), Día del Controlador Aéreo, Día de los Derechos Cívicos de la Mujer, Día Mundial de Concienciación de Duchenne y Día de los Pelirrojos.",
	"8 de Septiembre":"Fundación de Maracaibo (1529), Fundación del Banco Central de Venezuela (1939), Día Mundial de la Fisioterapia, Día Mundial Contra la Fibrosis Quística, Día Mundial de la Alfabetización, Día de El Chavo del 8 y Festividad de la Virgen del Valle.",
	"9 de Septiembre":"Sale el juego Mario Bross (1983) y Día Mundial de la Agricultura.",
	"10 de Septiembre":"Nace Luis Razetti (1862) y Día Mundial para la Prevención del Suicidio.",
	"11 de Septiembre":"Se funda La Universidad del Zulia - LUZ (1891), Nace Jacinto Convit (1913), Nace Adam West (1928), Muere Salvador Allende (1973), Muere José Antonio Calcaño (1978), Día Panamericano del Maestro y Festividad de la Virgen de Coromoto.",
	"12 de Septiembre":"Nace Aníbal Nazoa (1928), Día de las Naciones Unidas para la Cooperación Sur-Sur, Día Internacional de la Salud Bucodental y Día Internacional de Acción Contra la Migraña.",
	"13 de Septiembre":"Nace Rafael Arévalo González (1866), Fundación de Acción Democrática - AD (1941), Día Mundial Contra la Sepsis, Día del Profesor de Natación y Día Internacional del Chocolate.",
	"14 de Septiembre":"Fundación de Barquisimeto (1552), Nace Alejandro de Humboldt (1769), Nace Vicente Lecuna (1870), Nace Mario Benedetti (1920), Se funda La Organización de Países Exportadores de Petróleo - OPEP (1960) y Día Internacional de la Imagen de la Mujer en Rechazo a la Publicidad Sexista.",
	"15 de Septiembre":"Nace Mario Briceño Iragorry (1897), Muere Isaías Medina Angarita (1953), Muere Aldemaro Romero (2007), Día Internacional de la Democracia, Día Mundial Contra el Linfoma y Día Internacional del Reguetón.",
	"16 de Septiembre":"Muere Antonio Arraiz (1962), Fundación de Santa Elena de Uairén (1923) y Día Internacional de La Preservación de La Capa de Ozono.",
	"17 de Septiembre":"Muere Juan de Carvajal (1546), Muere Vicente Salías (1814), Día Mundial del Donante de Médula Ósea y Sangre de Cordón Umbilical y Día del Psicopedagogo.",
	"18 de Septiembre":"Nace José Tomás Boves (1782), Nace Tomás de Heres (1795), Muere Armando Reverón (1954) y Día Mundial de la Ética Médica.",
	"19 de Septiembre":"Nace José Félix Ribas (1775), Nace Lisandro Alvarado (1858), Suena por primera vez el Alma Llanera (1914), Muere Caracciolo Parra Pérez (1964) y Día del Instrumentador Quirúrgico.",
	"20 de Septiembre":"Primera Edición del Festival de Cannes (1946), Muere Marcos Pérez Jiménez (2001), Día Internacional de la Libertad y Día Internacional del Deporte Universitario.",
	"21 de Septiembre":"Nace Matea Bolívar - La Negra Matea (1773), Nace Leonard Cohen (1934), Día Mundial Contra el Alzheimer y Día Internacional de la Paz.",
	"22 de Septiembre":"Nace Mariano de Talavera (1777), Venezuela se separa definitivamente de la Gran Colombia (1830), Nace José Humberto Quintero (1902), Nace Harry Almela (1953), Muere Marcel Marceau (2007), Día Mundial Contra la Leucemia Mieloide Crónica, Día del Electricista y Día Mundial Sin Automóviles.",
	"23 de Septiembre":"Nace Lino de Clemente (1767), Nace Fermín Toro (1807), Muere Pablo Neruda (1973), Se lanza la primera versión de Android (2008), Día Mundial del Síndrome de las Piernas Inquietas (SPI), Día Internacional de la Bisexualidad y Día Internacional Contra la Explotación Sexual y el Tráfico de Mujeres, Niñas y Niños.",
	"24 de Septiembre":"Nace José Félix Blanco (1782) y Nace Juan Beroes (1914).",
	"25 de Septiembre":"Creación de La Real Compañía Guipuzcoana de Caracas (1728), Nace Luisa Cáceres de Arismendi (1799) y Día Mundial del Farmacéutico.",
	"26 de Septiembre":"Día Interamericano de las Relaciones Públicas, Día Internacional para la Eliminación Total de las Armas Nucleares, Creación del Comando Estratégico Operacional de la Fuerza Armada Nacional Bolivariana (CEOFANB) (2003) y Día Mundial de Prevención del Embarazo No Planificado en Adolescentes.",
	"27 de Septiembre":"Muere Luis Brión (1821), Nace José Manuel Díaz Márquez “Joselo” (1936), Sale el Buscador de Google (1998), Muere Hugh Hefner (2017), Día Mundial del Turismo y Día Nacional del Licenciado en Contaduría Pública.",
	"28 de Septiembre":"Día Mundial Contra la Rabia, Alexander Fleming descubre la Penicilina (1928), Día Internacional del Productor de Seguros y Día Mundial del Acceso a la Información.",
	"29 de Septiembre":"Nace Miguel de Cervantes (1547), Primer Vuelo Aéreo sobre Venezuela (1912), Se Inaugura el Teleférico de Caracas (1955), Día Mundial del Corazón, Día Internacional del Café y Fiesta de los Tres Arcángeles, San Miguel, San Gabriel y San Rafael.",
	"30 de Septiembre":"Muere Atanasio Girardot (1813), Día Internacional de la Traducción y Día de La Secretaria.",
	"1 de Octubre":"Muere Juan Vicente González (1866), Muere Juan José Flores (1864), Nace Julio Jaramillo (1935), Muere Enrique Bernardo Núñez (1964), Día Internacional de las Personas de Edad, Día Nacional del Cacao Venezolano, Día Internacional de la Música y Día Internacional del Vegetarianismo.",
	"2 de Octubre":"Día Mundial de la Educación Social, Día del Dietista y Nutricionista y Día Internacional de la No Violencia.",
	"3 de Octubre":"Batalla de las Trincheras (1813), Día Internacional del Mosquetero, Día del Odontólogo, Día del Vecino y Día de las Asociaciones de Vecinos.",
	"4 de Octubre":"Se implementa el Calendario Gregoriano (1582), Muere Juan Antonio Pérez Bonalde (1892), Nace Violeta Parra (1917), Nace Rocío Dúrcal (1944), Muere Mercedes Sosa (2009), Día Mundial de los Animales y Festividad de San Francisco de Asís.",
	"4 al 10 de Octubre":"Semana Mundial del Espacio.",
	"5 de Octubre":"Nace Teresa de la Parra (1889), Muere Steve Jobs (2011), Día Mundial de los Docentes y Día Internacional de la Educación Vial.",
	"6 de Octubre":"Muere José Antonio de Armas Chitty (1995) y Día Internacional del Agua.",
	"7 de Octubre":"Muere María Antonia Bolívar Palacios (1842), Día Mundial por el Trabajo Decente y Festividad de la Virgen del Rosario.",
	"8 de Octubre":"Día del Estudiante Solidario.",
	"9 de Octubre":"Fundación de Trujillo (1557), Fundación de Mérida (1558), Muere Ernesto Che Guevara (1967) y Día Mundial del Correo.",
	"10 de Octubre":"Nace Francisco Antonio Risquez (1856), Día del Soldado Venezolano, Día del Oftalmólogo, Día Mundial de la Salud Mental y Día Internacional Contra la Pena de Muerte.",
	"11 de Octubre":"Batalla de El Yagual (1816), Día Internacional de la Niña y Festividad de San Juan XXIII.",
	"12 de Octubre":"Nace Cipriano Castro (1858), Se crea La Primera Compañía Petrolera en Venezuela - La Petrolia del Táchira (1878), Nace Pastor Oropeza (1901), Día de la Resistencia Indígena o Día de la Raza, Día de la Lengua Española, Día Mundial Contra la Artritis y Festividad de la Virgen del Pilar.",
	"13 de Octubre":"Simón Bolívar escribe “Mi Delirio Sobre el Chimborazo” (1822), Día Internacional para la Reducción de los Desastres y Día Mundial Contra la Trombosis.",
	"14 de Octubre":"Simón Bolívar recibe el título de “Libertador de Venezuela” (1813), Se Filma la Primera Película de la Historia “La Escena del Jardín de Roundhay” (1888), Nace Isaac J. Pardo (1905), Día Mundial de la Espirometría, Día Mundial del Donante de Órganos y Tejidos y Día Mundial de la Normalización.",
	"15 de Octubre":"Nace Juan Vicente Bolívar y Ponte (1726), Muere Andrés Bello (1865), Día Internacional de las Mujeres Rurales, Día Mundial del Lavado de Manos y Festividad de Santa Teresa de Jesús.",
	"16 de Octubre":"Es Fusilado Manuel Piar (1817), Muere Rufino Blanco Fombona (1944), Es nombrado Papa Juan Pablo II (1978), Día Mundial de la Alimentación, Día del Anestesiólogo, Día Internacional de la Anestesiología, Día Internacional de la RCP y Día Mundial del Pan.",
	"17 de Octubre":"Muere Ana María de Campos (1828), Día Internacional para la Erradicación de la Pobreza, Día de la Dignificación de los Motorizados y Día Mundial Contra el Dolor.",
	"18 de Octubre":"Golpe de Estado Contra Medina Angarita (1945), Día Mundial de la Menopausia y Día Mundial de la Protección de la Naturaleza.",
	"19 de Octubre":"Se Inaugura el Museo de Bellas Artes de Caracas (1917), Nace Eugenio Montejo (1938) y Día Mundial Contra el Cáncer de Mama.",
	"20 de Octubre":"Nace Carlos Augusto León (1914), Día Internacional del Chef, Día del Pediatra, Día Mundial Contra la Osteoporosis, Día Internacional del Controlador Aéreo y Día Mundial de la Estadística.",
	"21 de Octubre":"Nace Francisco Antonio Zea (1770), Fundación de la Ciudad de Los Teques (1777), Nace Celia Cruz (1925), Muere José Ignacio Cabrujas (1995) y Día Mundial del Ahorro Energético.",
	"22 de Octubre":"Día Mundial del Conocimiento de la Tartamudez, Día Internacional de la Oscilación, Día Internacional de la Medicina Natural o Tradicional y Festividad de San Juan Pablo II.",
	"23 de Octubre":"Aparece el Original del Acta de la Independencia de Venezuela (1907), Día Mundial de Acción para la Supervivencia Infantil y Día del Mol.",
	"24 de Octubre":"Nace Anton van Leeuwenhoek (1632), Nace Rafael Urdaneta (1788), Se funda el Primer Equipo de Fútbol de la Historia El Sheffield Football Club (1857), Se funda La Organización de las Naciones Unidas - ONU (1945), Se funda La Universidad Católica Andrés Bello - UCAB (1953), Muere Harry Almela (2017), Día de las Naciones Unidas, Día Mundial Contra la Poliomielitis, Día Mundial de Información sobre el Desarrollo, Día Internacional de las Bibliotecas y Día del Trabajador Gráfico.",
	"24 al 30 de Octubre":"Semana del Desarme.",
	"25 de Octubre":"Muere Manuel Gual (1800), Nace Pablo Picasso (1881), Día Mundial del Karate, Día del Zapatero, Día Mundial de la Pasta y Día Mundial de las Personas de Talla Baja.",
	"26 de Octubre":"Nace José Gregorio Hernández (1864), Nace Miguel Otero Silva (1908), Se funda el Equipo Navegantes del Magallanes (1917), Francisco Morochito Rodríguez gana la Primera Medalla de Oro Olímpica de Venezuela (1968), Día Internacional de la Prevención de Quemaduras, Día Mundial Contra el Daño Cerebral Adquirido y Día de la Suegra.",
	"27 de Octubre":"Día Mundial del Patrimonio Audiovisual, Día Internacional de la Corrección, Día del Corrector de Textos y Día Mundial de la Terapia Ocupacional.",
	"28 de Octubre":"Nace Simón Rodríguez (1769), Nace José Tadeo Monagas (1784), Inauguración del Panteón Nacional (1875), La Sociedad Patriótica dona al Estado Venezolano La Casa Natal del Libertador Simón Bolívar (1912), Nace Bill Gates (1955), Día del Ingeniero, Día Mundial de la Animación, Día del Bibliotecario Escolar y Día de San Judas Tadeo.",
	"29 de Octubre":"Día Mundial Contra el Ictus, Día Mundial Contra la Psoriasis y Día Mundial Contra el ACV.",
	"30 de Octubre":"Muere Bartolomé Salom (1863).",
	"31 de Octubre":"Nace Alí Primera (1941), Pacto de Punto Fijo (1958), Muere José Manuel Briceño Guerrero (2014), Día Mundial del Ahorro, Día del Poeta Virtual, Día Mundial de las Ciudades y Día Internacional del Arroz.",
	"1 de Noviembre":"Sublevación de los Indios Quiriquires (1600), Nace María Antonia Bolívar Palacios (1777), Inicia la Guerra de Vietnam (1955), Día Mundial de la Ecología y Día de todos Los Santos.",
	"2 de Noviembre":"Muere César Rengifo (1980), Muere Rafael Monasterios (1961), Día Internacional para Poner Fin a la Impunidad de los Crímenes Contra Periodistas y Día de Los Fieles Difuntos.",
	"3 de Noviembre":"Fundación de Guanare (1591), Se emite la Primera Cédula de Identidad en Venezuela al General Isaías Medina Angarita con el número de cédula 0001 (1942), Día Internacional del Joyero y Relojero, Día Mundial del Sándwich y Día Internacional del Anime.",
	"4 de Noviembre":"Día de la Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura (UNESCO).",
	"5 de Noviembre":"Nace Arístides Rojas (1826), Día Mundial de Concienciación sobre los Tsunamis y Día Internacional del Payaso.",
	"6 de Noviembre":"Nace Pedro Antonio Ríos Reyna (1905), Día Contra el Paludismo en las Américas y Día Internacional para la Prevención de la Explotación del Medio Ambiente en la Guerra y los Conflictos Armados.",
	"7 de Noviembre":"Nace Marie Curie (1867), Se Inaugura en la Plaza Bolívar de Caracas La Estatua Ecuestre del Libertador Simón Bolívar (1874), Nace Albert Camus (1913), Día Internacional de la Física Médica, Día del Obrero Educacional y Día del Periodista Deportivo.",
	"8 de Noviembre":"Se Inaugura el Museo del Louvre (1793), Muere Cristóbal Rojas (1890), Nace Lucila Palacios (1902), Muere Ricardo Aguirre (1969), Se Inaugura la Central Hidroeléctrica Raúl Leoni - Guri, hoy llamada Central Hidroeléctrica Simón Bolívar (1986), Día Mundial de la Radiología, Día Mundial del Urbanismo, Día Internacional de la Dislexia, Día Mundial de la Filantropía y Día del Gaitero.",
	"9 de Noviembre":"Batalla de Los Magueyes (1814), Caída del Muro de Berlín (1989), Día Internacional del Inventor y Día Internacional Contra el Fascismo y el Antisemitismo.",
	"10 de Noviembre":"Nace Martín Lutero (1483) y Día Mundial de la Ciencia para la Paz y el Desarrollo.",
	"11 de noviembre":"Fin de la Primera Guerra Mundial (1918), Día de Luis Aparicio (Primer venezolano exaltado al Salón de la Fama del Béisbol) y Día Mundial del Shopping.",
	"11 al 17 de Noviembre":"Semana Internacional de la Ciencia y la Paz.",
	"12 de Noviembre":"Nace Alirio Díaz (1923), Día Mundial Contra la Neumonía y Día Mundial de la Lucha Contra la Obesidad.",
	"13 de Noviembre":"Asesinato de Delgado Chalbaud (1950), Día Mundial de la Amabilidad o Bondad, Día Internacional del Récord Guinness y Festividad de la Virgen del Socorro de Valencia.",
	"14 de Noviembre":"Nace José Antonio Anzoátegui (1789), Nace Alejandro Próspero Reverend (1796) y Día Mundial Contra la Diabetes.",
	"15 de Noviembre":"Muere José Antonio Anzoátegui (1819), Se funda La Universidad de Carabobo - UC (1892), Nace Billo Frómeta (1915) y Día Mundial Sin Alcohol.",
	"16 de Noviembre":"Se funda la Unesco (1945), Día Internacional del Patrimonio Mundial, Día Internacional para la Tolerancia y Día del Flamenco.",
	"17 de Noviembre":"Día del Economista, Día Mundial del Niño Prematuro y Día Internacional Contra el Cáncer de Pulmón.",
	"18 de Noviembre":"Muere José Tadeo Monagas (1868), Es creado Mickey Mouse (1928), Día de la Alimentación en Venezuela y Día de la Virgen del Rosario de Chiquinquirá.",
	"19 de Noviembre":"Día Mundial del Retrete, Día Internacional del Hombre y Día Mundial para la Prevención del Abuso Contra los Niños.",
	"20 de Noviembre":"Simón Bolívar Decreta la Octava Estrella en la Bandera Nacional (1817), Se lanza la primera versión de Windows 1.0 (1985), Día Internacional de Los Derechos del Niño y Día de la Industrialización de África.",
	"21 de Noviembre":"Disolución de la Gran Colombia (1831), Nace Luis Armando Roche (1938), Se funda La Universidad de Oriente - UDO (1958), Día Mundial Contra la Espina Bífida, Día Mundial de la Televisión, Día del Estudiante Universitario y Día Mundial del Vestido.",
	"22 de Noviembre":"Nace Rafael Monasterios (1884), Día del Psicólogo y Día Internacional del Músico.",
	"23 de Noviembre":"Muere Manuela Sáenz (1856), Día Nacional del Transportista, Día Internacional del Asesor de Imagen y Día Internacional de la Palabra como Vínculo de la Humanidad.",
	"24 de Noviembre":"Nace José Rafael Revenga (1786), Charles Darwin publica El Origen de Las Especies (1859), Golpe de Estado Contra Rómulo Gallegos (1948) y Día Mundial del Dietista-Nutricionista.",
	"25 de Noviembre":"Muere Fidel Castro (2016) y Día Internacional de la Eliminación de La Violencia Contra la Mujer.",
	"26 de Noviembre":"Se firma en Trujillo el Armisticio y el Tratado de Regularización de la Guerra entre España y Colombia (1820), Nace Juan Pablo Rojas Paúl (1826), Muere Conny Méndez (1979) y Día Mundial Contra el Uso Indiscriminado de Agroquímicos.",
	"27 de Noviembre":"Fundación de Cumaná (1515), Descubrimiento de las Fuentes del Orinoco (1951), Intentona Golpista Contra Carlos Andrés Pérez (1992), Muere Alfredo Boulton (1995), Día de la Aviación Militar Nacional Bolivariana, Día Contra de la Dermatitis Atópica y Festividad de La Virgen de La Medalla de La Milagrosa.",
	"28 de Noviembre":"Nace Inocente Carreño (1919), Muere Roberto Gómez Bolaños - Chespirito (2014) y Día Mundial de las Personas Sin Hogar.",
	"29 de Noviembre":"Nace Andrés Bello (1781), Día del Escritor y Día Internacional de Solidaridad con el Pueblo Palestino.",
	"30 de Noviembre":"Muere Francisco Linares Alcántara (1878), Nace José Antonio de Armas Chitty (1908), Muere Laudelino Mejías (1963), Día de la Seguridad Informática y Día Internacional de Lucha Contra los Trastornos Alimentarios.",
	"1 de Diciembre":"Muere Alejandro Próspero Reverend (1881), Se funda la Federación Venezolana de Fútbol - FVF (1925), Se enciende por primera vez la Nueva Cruz del Ávila (1982), Día del Farmacéutico, Día Panamericano del Bioquímico, Día Panamericano del Químico, Día Mundial de la Lucha contra el SIDA, Día Mundial sobre el Uso del Cinturón de Seguridad, Día del Sufragio Universal y Día del Ama de Casa.",
	"2 de Diciembre":"Nace Emilio Arévalo Cedeño (1882) y Día Internacional para la Abolición de la Esclavitud.",
	"3 de Diciembre":"Muere Gregor MacGregor (1845), Primeras Elecciones Regionales (1989), Día Internacional de las Personas con Discapacidad, Día Internacional del Médico, Día Mundial del No Uso de Plaguicidas y Día Internacional del 3D.",
	"4 de Diciembre":"Día de Santa Bárbara.",
	"5 de Diciembre":"Batalla de Araure (1813), Batalla de Urica (1814), Muere Miguel José Sanz (1814), Muere José Tomás Boves (1814), Nace Walt Disney (1901), Muere Nelson Mandela (2013), Los Cantos de Trabajo de Los Llanos de Colombia y Venezuela son agregados a la Lista del Patrimonio Cultural Inmaterial de la Unesco (2017), Día del Profesor Universitario, Día de la Sonrisa, Día Internacional de los Voluntarios, Día Mundial del Suelo y Día Internacional del Retocador Fotográfico.",
	"6 de Diciembre":"Inauguración de Las Torres del Centro Simón Bolívar (1954) y Festividad de San Nicolás de Bari.",
	"7 de Diciembre":"Fundación del Tocuyo (1545), Fundación de Maturín (1760), Nace Ambrosio Plaza (1791) y Día de la Aviación Civil Internacional.",
	"8 de Diciembre":"Nace Vicente Emilio Sojo (1887), Se funda La Unión de Naciones Suramericanas - UNASUR (2004), Día del Bartender y Día de la Inmaculada Concepción.",
	"9 de Diciembre":"Nace María de la Concepción Palacios y Blanco (1758), Nace José Ramón Yepes (1822), Batalla de Ayacucho (1824), Día Internacional contra la Corrupción, Día Mundial de la Informática, Día Mundial del APL (Analista de Planificación Logística) y Día Internacional para la Conmemoración y Dignificación de las Víctimas del Crimen de Genocidio y para la Prevención de ese Crimen.",
	"10 de Diciembre":"La Última Proclama del Libertador (1830), Muere José Ángel Lamas (1814), Ejecutado José Leonardo Chirino (1796), Batalla de Santa Inés (1859), Día Internacional de los Derechos Animales y Día de la Declaración Universal de los Derechos Humanos.",
	"11 de Diciembre":"Nace Francisco Rodríguez del Toro (1761), Nace Renny Ottolina (1928), Día Nacional del Juez, Día Nacional del Locutor, Día Internacional de las Montañas y Día del Tango.",
	"12 de Diciembre":"Día de Nuestra Señora de Guadalupe y Día de la Cobertura Universal de Salud.",
	"13 de Diciembre":"Muere Argimiro Gabaldón (1964) y Festividad de Santa Lucía.",
	"14 de Diciembre":"Se celebra las Primeras Elecciones Presidenciales Libres y Directas en Venezuela (1947) y Se funda La Alianza Bolivariana para América - ALBA (2004).",
	"15 de Diciembre":"Nace Carlos Soublette (1789), Manifiesto de Cartagena (1812), Muere José Francisco Bermúdez (1831), Nace Cristóbal Rojas (1858), Plebiscito de Pérez Jiménez (1957), Muere Walt Disney (1966), Referéndum Aprobatorio de la Constitución de la República Bolivariana de Venezuela (1999), Día del Poder Popular Constituyente y Día del Camionero.",
	"16 de Diciembre":"Nace Diego Bautista Urbaneja (1782), Se funda A.C. Milan (1899) y Día del Dibujante.",
	"17 de Diciembre":"Se Decreta la Creación de la Gran Colombia (1819), Muere El Libertador Simón Bolívar (1830), Orville Wright a bordo del Flyer I realiza el Primer Vuelo con Motor (1903) y Se estrena la Serie Los Simpson (1989).",
	"18 de Diciembre":"Nace José Rafael Pocaterra (1889), Día de la Lengua Árabe y Día Internacional del Migrante.",
	"19 de Diciembre":"El Libertador Simón Bolívar promulgó el Decreto de Chuquisaca (1825) y Se crea El Parque Nacional Mochima (1973).",
	"20 de Diciembre":"Se crea la Primera Página Web (1990) y Día Internacional de la Solidaridad Humana.",
	"21 de Diciembre":"Se funda la Ciudad de Santo Tomé de Guayana actual Ciudad Bolívar (1595), Es sancionada la Primera Constitución de Venezuela y de América Latina (1811), Inauguración del Monumento a la Virgen de la Paz (1983) y Celebración del Espíritu de la Navidad.",
	"22 de Diciembre":"Se funda la Universidad Central de Venezuela - UCV (1721) y Nace Teresa Carreño (1853).",
	"23 de Diciembre":"Muere Fermín Toro (1865).",
	"24 de Diciembre":"Nace Gregor MacGregor (1786).",
	"25 de Diciembre":"Natividad de Nuestro Señor Jesucristo, Muere Charles Chaplin (1977) y Disolución de la Unión Soviética.",
	"26 de Diciembre":"Festividad de San Esteban.",
	"27 de Diciembre":"Nace Manuela Sáenz (1797), Simón Bolívar llega a la población colombiana de Mompox (1812), Se crea el Fondo Monetario Internacional - FMI (1945), Se funda la Liga Venezolana de Béisbol Profesional - LVBP (1945) y Festividad de San Benito de Palermo.",
	"28 de Diciembre":"Muere Vicente Gerbasi (1992) y Día de los Santos Inocentes.",
	"29 de Diciembre":"Nace Charles Goodyear (1800).",
	"30 de Diciembre":"Día Internacional del Cine Indio.",
	"31 de Diciembre":"Se inaugura el Primer Cable Submarino Tendido de la historia entre las ciudades de Dover-Inglaterra y Calais-Francia (1851) y Estados Unidos entrega la administración del Canal de Panamá a la República de Panamá (1999)."
};